spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: zk-server
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        register: true
        enabled: true
        instance-id: 1
server:
  port: 6061
