spring:
  application:
    name: zk-client
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        register: true
        enabled: true
        instance-id: 1
server:
  port: 6062
