spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: zk-server
 
aaa:
  bbb: "bbbb"
